    name: 'trigger workflow'

    on:
        push:
            branches:
                - main
            paths:
                - README.md

    jobs:
        build:
            runs-on: ubuntu-latest

            steps:
                - name: Test
                  run: |
                    curl -L \
                      -X POST \
                      -H "Accept: application/vnd.github+json" \
                      -H "Authorization: Bearer ${{secrets.ACTIONS_KEY}} \
                      -H "X-GitHub-Api-Version: 2022-11-28" \
                      https://api.github.com/repos/poornendushukla/leetcode_questions/dispatches \
                      -d '{"event_type":"Trigger Workflow"}'
                      
                - uses: actions/checkout@v3

