    name: 'trigger workflow'

    on:
        push:
            branches:
                - main
            paths:
                - Readme.md

    jobs:
        build:
            runs-on: ubuntu-latest

            steps:
                - name: Test
                  run: |
                    curl -X POST https://api.github.com/repos/poornendushukla/leetcode_questions/dispatches /
                      -H 'Accept:application/vnd.github.everest-preview+json' \
                      -u ${{secrets.GITHUB_TOKEN}} \
                      --data '{"event-type":"Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
                - uses: actions/checkout@v3

